# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jim Council
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
js:
 - /assets/js/jquery-1.11.2.js
 - /assets/js/function.js
 - /assets/js/bootstrap.js
 - /assets/js/modernizr.js
 - /assets/js/slick.js
 - /assets/js/stickyheader.js
 - /assets/js/mega-dropdown.js
 - /assets/js/backtotop.js
 - /assets/js/parallax.js
 - /assets/js/animation.js
 - /assets/js/counter.js
 - /assets/js/number-counter.js
 - /assets/js/accordian.js
 - /assets/js/bootstrapValidator.js
 - /assets/js/formValidation.js
 - /assets/js/revoluation/jquery.themepunch.tools.min.js
 - /assets/js/revoluation/jquery.themepunch.revolution.min.js
 - /assets/js/revoluation/revolution.extension.layeranimation.min.js
 - /assets/js/revoluation/revolution.extension.migration.min.js
 - /assets/js/revoluation/revolution.extension.navigation.min.js
 - /assets/js/revoluation/revolution.extension.parallax.min.js
 - /assets/js/revoluation/revolution.extension.slideanims.min.js
 - /assets/js/revoluation/revoluationfunction.js
sass:
    style: compressed
    sass_dir: _sass
gems:
  - jekyll-feed
  - jekyll-coffeescript
exclude:
  - Gemfile
  - Gemfile.lock
